from rdkit import Chem
from rdkit.Chem import Draw, rdFMCS
from rdkit.Chem.Draw import rdMolDraw2D


def draw_mols_to_grid(mols, names, highlight_atoms_list=None, highlight_bonds_list=None, scaling=1.0):
    if highlight_atoms_list is None:
        highlight_atoms_list = [[] for _ in mols]
    if highlight_bonds_list is None:
        highlight_bonds_list = [[] for _ in mols]


    draw_options = rdMolDraw2D.MolDrawOptions()
    draw_options.useBWAtomPalette()  # Enable black-and-white palette
    svg_obj = Draw.MolsToGridImage(
        mols, 
        molsPerRow=len(mols), 
        subImgSize=(int(200 * scaling), int(200 * scaling)), 
        legends=names, 
        useSVG=True,
        highlightAtomLists=highlight_atoms_list,
        highlightBondLists=highlight_bonds_list,
        drawOptions=draw_options,
        returnPNG=False  # Ensure SVG mode
    )
    return svg_obj._repr_svg_()


def draw_compounds(compounds, show_names=True, scaling=1.0):
    # If a compound has no SMILES, use * so that a molecule plot
    # is generated by RDKit and the molecule name is shown as a legend
    names, smiles = zip(*compounds) if compounds else ([], [])
    if show_names is False:
        names = ['' for _ in names]
    mols = [Chem.MolFromSmiles(s if s else "*") for s in smiles]
    svg = draw_mols_to_grid(mols, names, scaling=scaling)
    return svg


def draw_compounds_with_substruct_flexible(compounds, substruct_smiles, show_names=True, scaling=1.0):
    names, smiles = zip(*compounds) if compounds else ([], [])
    if show_names is False:
        names = ['' for _ in names]
    mols = [Chem.MolFromSmiles(s if s else "*") for s in smiles]

    q = Chem.MolFromSmiles(substruct_smiles)
    if q is None:
        return draw_mols_to_grid(mols, names)

    highlight_atoms_list = []
    highlight_bonds_list = []

    for mol in mols:
        if mol is None:
            highlight_atoms_list.append([])
            highlight_bonds_list.append([])
            continue

        # METHOD: MCS (Maximum Common Substructure) - handles bond changes
        mcs_result = rdFMCS.FindMCS([q, mol], timeout=1000)
        mcs_smarts = mcs_result.smartsString
        
        if mcs_smarts != '':  # Found common substructure
            mcs_query = Chem.MolFromSmarts(mcs_smarts)
            matches = mol.GetSubstructMatches(mcs_query, uniquify=False)
            
            if matches:
                all_atoms = set()
                all_bonds = set()
                
                for match in matches:
                    atoms = list(match)
                    all_atoms.update(atoms)
                    match_set = set(atoms)
                    for bond in mol.GetBonds():
                        a1 = bond.GetBeginAtomIdx()
                        a2 = bond.GetEndAtomIdx()
                        if a1 in match_set and a2 in match_set:
                            all_bonds.add(bond.GetIdx())
                
                highlight_atoms_list.append(list(all_atoms))
                highlight_bonds_list.append(list(all_bonds))
            else:
                highlight_atoms_list.append([])
                highlight_bonds_list.append([])
        else:
            highlight_atoms_list.append([])
            highlight_bonds_list.append([])

    svg = draw_mols_to_grid(
        mols, names,
        highlight_atoms_list=highlight_atoms_list,
        highlight_bonds_list=highlight_bonds_list,
        scaling=scaling,
    )

    return svg